apiVersion: v1
kind: Pod
metadata:
  name: pvc-teste
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: html
  volumes:
    - name: html
      persistentVolumeClaim:
        claimName: fake-pvc
