---
- name: Instalar Docker na VM Ubuntu
  hosts: azure
  become: yes

  tasks:
    - name: Instalar dependências
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Adicionar chave GPG oficial do Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Adicionar repositório do Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Instalar Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Garantir que o serviço Docker está ativo
      service:
        name: docker
        state: started
        enabled: yes
