name: Testar Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Verificar se o segredo AZURE_CREDENTIALS está definido
        run: |
          if [ -z "${{ secrets.AZURE_CREDENTIALS }}" ]; then
            echo "❌ Segredo NÃO está definido!"
            exit 1
          else
            echo "✅ Segredo AZURE_CREDENTIALS está definido!"
          fi
