name: Testar Secrets

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Testando se AZURE_CREDENTIALS existe
        run: echo "Segredo existe!"
        env:
          TESTE: ${{ secrets.AZURE_CREDENTIALS }}
